import React from 'react';
import './termsAndPrivacy.css';


const TermsAndPrivacy = () => {


return (
    <div className="container px-4 py-8">
        {/* Terms & Conditions Section */}
        <h1 className="text-3xl font-bold mb-4">Terms & Conditions</h1>
        <p className="mb-2">
            1. This document is an electronic record in terms of the Information Technology Act, 2000, and rules thereunder as applicable, and the amended provisions relating to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
        </p>
        <p className="mb-2">
            2. This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy, and Terms of Use for access or usage of our Platform.
        </p>
        <p className="mb-2">
            3. The Platform is owned and operated by LETS QUIZ, having its registered office at FIRST FLOOR, 282, Kombakkam, Puducherry Villianur Road, Pondicherry, India. All references to "we," "us," and "our" shall mean LETS QUIZ.
        </p>
        <p className="mb-2">
            4. By accessing or using the Platform, you agree to be bound by these Terms of Use and any applicable policies incorporated by reference herein, forming a legally binding contract with LETS QUIZ.
        </p>
        <p className="mb-4">
            5. Your continued use of the Platform following any modification of the terms will mean you accept those modifications. We encourage you to review these terms periodically.
        </p>

        {/* Privacy Policy Section */}
        <h2 className="text-2xl font-semibold mb-3">Privacy Policy</h2>
        <p className="mb-2">
            <strong>Introduction:</strong> This Privacy Policy explains how LETS QUIZ collects, uses, shares, and protects your personal information through the website www.letsquiz.org. By using our Platform, you consent to the data practices described in this policy.
        </p>
        <p className="mb-2">
            Our Platform is intended for use within India, and all data collected will be primarily stored and processed in India.
        </p>

        {/* Collection Section */}
        <h3 className="text-xl font-semibold mt-4 mb-2">1. Collection of Information</h3>
        <p className="mb-2">
            We collect personal data to provide our services efficiently. The types of personal information collected include:
            <ul className="list-disc pl-5">
                <li>Name, date of birth, and contact information (address, phone number, email ID)</li>
                <li>Financial information (such as bank account or credit card details)</li>
                <li>Device and log information, cookies, and usage data</li>
            </ul>
        </p>
        <p className="mb-2">
            This information may be collected directly from you or automatically when you interact with our Platform.
        </p>

        {/* Usage Section */}
        <h3 className="text-xl font-semibold mt-4 mb-2">2. Usage of Information</h3>
        <p className="mb-2">
            We use your personal data to:
            <ul className="list-disc pl-5">
                <li>Provide and improve our services</li>
                <li>Enhance your user experience and facilitate payments</li>
                <li>Ensure security and prevent fraud</li>
                <li>Send marketing communications, which you can opt-out of at any time</li>
            </ul>
        </p>

        {/* Sharing Section */}
        <h3 className="text-xl font-semibold mt-4 mb-2">3. Sharing of Information</h3>
        <p className="mb-2">
            We may share your information with:
            <ul className="list-disc pl-5">
                <li>Our affiliates and third-party partners for service delivery</li>
                <li>Government agencies or legal authorities, if required by law</li>
                <li>Other entities in the case of a merger, acquisition, or asset sale</li>
            </ul>
        </p>

        {/* Security Precautions */}
        <h3 className="text-xl font-semibold mt-4 mb-2">4. Security Precautions</h3>
        <p className="mb-2">
            We implement industry-standard security measures to protect your data. However, no method of internet transmission is 100% secure, and we cannot guarantee the absolute security of your information.
        </p>

        {/* Data Retention and Deletion */}
        <h3 className="text-xl font-semibold mt-4 mb-2">5. Data Retention and Deletion</h3>
        <p className="mb-2">
            You may request to delete your account by contacting us. We retain some information as necessary to comply with our legal obligations, resolve disputes, or enforce our agreements.
        </p>

        {/* User Rights Section */}
        <h3 className="text-xl font-semibold mt-4 mb-2">6. Your Rights</h3>
        <p className="mb-2">
            You have the right to:
            <ul className="list-disc pl-5">
                <li>Access and update your personal information</li>
                <li>Delete your personal data, subject to applicable laws</li>
                <li>Manage communication preferences via account settings</li>
            </ul>
        </p>

        {/* Consent Section */}
        <h3 className="text-xl font-semibold mt-4 mb-2">7. Consent</h3>
        <p className="mb-4">
            By using our Platform, you consent to our data collection and usage practices. If you do not agree to this policy, please refrain from using our services.
        </p>

        {/* Refund and Cancellation Policy */}
        <h2 className="text-2xl font-semibold mb-3">Refund and Cancellation Policy</h2>
        <p className="mb-2">
            Our refund and cancellation policy is designed to be fair and transparent. If you wish to cancel a subscription or request a refund, please contact our support team within the specified time frame. Refunds will be processed as per our policy guidelines.
        </p>

        {/* Contact Information Section */}
        <h2 className="text-2xl font-semibold mb-3">Contact Information</h2>
        <p className="mb-2">
            If you have any questions or concerns regarding our Terms & Conditions or Privacy Policy, please contact us:
        </p>
        <p className="mb-2">
            <strong>LETS QUIZ</strong><br />
            First Floor, 282, Kombakkam, Puducherry Villianur Road, Pondicherry, India<br />
            Phone: +91 6380899518 (Monday - Friday, 10:00 AM - 6:00 PM)
        </p>

        <p className="text-sm text-gray-600">
            Note: This document was last updated on {new Date().toLocaleDateString()}. We reserve the right to modify these terms and policies at any time.
        </p>
    </div>
);
};

export default TermsAndPrivacy;
